### ISSUE TITLE
[FR] Let exclude function to receive window hundler

### ISSUE THREAD

**Issue by atusy** [tkmpypy/chowcho.nvim#10]
Currently, exclude function only receives buffer information.
I think there are use cases to exclude based on window information.

https://github.com/tkmpypy/chowcho.nvim/blob/3a9829ec6657bbd988565158b0e8fe1046858be5/lua/chowcho/init.lua#L105

Although it is easy enough to make a PR, it is difficult to design the API...

I show some ideas.
The latter two makes breaking changes, but I think they are affordable as the `exclude` option is added quite recently.

``` lua
-- add window hundler as 4-th arg
function(buf, bt, fname, win)

-- simplify to only receive buffer number and window hundler
function(bufnr, win)

-- squash everything into named table
function({...})
```

I would be happy to here @tkmpypy 's opinion.
Thank you!

**Comment by tkmpypy** [comment]
Hi @atusy 

Thanks for your input!

First, I think it would be better to clarify the default exclusion process and the user-defined exclusion function.
For example, a process like `buftype ~= "prompt"` or `fname ~= "" `.

It would be nice to be able to switch between these with a setting like `use_exclude_default`.

Also, the interface of the exclude API provided to users should be as simple as `function(bufnr, win)`.

If the default exclude process is not sufficient, users can write their own functions to this function to make it a simplified API while supporting various use cases.

**Comment by atusy** [comment]
@tkmpypy Thanks a lot! I opened a PR #11 based on your suggestion.
