### ISSUE TITLE
Invalid window id: 1056

### ISSUE THREAD

**Issue by cppcoffee** [tkmpypy/chowcho.nvim#13]
The nvim config:

```
map('n', '-', require('chowcho').run, { noremap = false })
```

When call `require('chowcho').run`, an error occurs:

```
E5108: Error executing lua: ...site/pack/packer/start/chowcho.nvim/lua/chowcho/init.lua:55: Invalid window id: 1056
stack traceback:
        [C]: in function 'nvim_win_get_width'
        ...site/pack/packer/start/chowcho.nvim/lua/chowcho/init.lua:55: in function 'calc_center_win_pos'
        ...site/pack/packer/start/chowcho.nvim/lua/chowcho/init.lua:101: in function <...site/pack/packer/start/chowcho.nvim/lua/chowcho/init.lua:88>
```

nvim version

```
% nvim --version
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
```

https://github.com/tkmpypy/chowcho.nvim/blob/main/lua/chowcho/init.lua#L55

Does it look like a problem with nvim?

**Comment by tkmpypy** [comment]
@cppcoffee 

I tried using [nevim v0.8.1](https://github.com/neovim/neovim/commit/935615ffeddee2839bb5ac92c3c8e30baa882923) in my environment and could not reproduce this issue. 

If you have specific instructions on how to operate and the minimum configuration where this issue occurs, you may be able to help.

You may also want to try using neovim's HEAD to isolate this issue and see if that solves it.

**Comment by cppcoffee** [comment]
It is not reproduced now, close issue.
