### ISSUE TITLE
An error occurs when I change the color scheme.

### ISSUE THREAD

**Issue by s-show** [tkmpypy/chowcho.nvim#18]
I'm using tkmpypy/chowcho.nvim, but when I change the color scheme to [modus-themes.nvim](https://github.com/miikanissi/modus-themes.nvim) and execute `require('chowcho').run()`, I get the following error.

```
E5108: Error executing lua: ...re/nvim/lazy/chowcho.nvim/lua/chowcho/selector/float.lua:109: bad argument #2 to 'format' (number expected, got nil)
stack traceback:
[C]: in function 'format'
...re/nvim/lazy/chowcho.nvim/lua/chowcho/selector/float.lua:109: in function 'highlight'
...are/nvim/lazy/chowcho.nvim/lua/chowcho/selector/init.lua:32: in function 'highlight'
....local/share/nvim/lazy/chowcho.nvim/lua/chowcho/init.lua:103: in function 'run'
/home/(username)/.config/nvim/lua/setting/chowcho-nvim.lua:48: in function </home/(username)/.config/nvim/lua/setting/chowcho-nvim.lua:47>
```

The error seems to be caused by the line 108 `local default = vim.api.nvim_get_hl(0, { name = hl.default })`, which gets the value of the color scheme.

To explain in more detail, `local default = vim.api.nvim_get_hl(0, { name = hl.default })` stores the value of `Special` in the `default` variable, but the value of `Special` in modus-themes.nvim is `{ link = “Type” }`, so the value of `default` becomes `{ link = “Type” }`. Even if I execute the `vim.api.nvim_get_hl(0, { name = “Special” })` command from the command line, the result is `{ link = “Type” }`.
(Link to "value of `Special` in modus-themes.nvim" -> [modus-themes.nvim](https://github.com/miikanissi/modus-themes.nvim/blob/ad9910a0e5055a00b1e14b507902b2a7a7fe449e/lua/modus-themes/theme.lua#L132)).

Then, `local c = string.format(“#%06x”, default.fg)` is executed, and I get a `bad argument #2 to 'format' (number expected, got nil)` error.

My settings are as follows, but it seems that the value set in `selector.float.color.border.active` is not being used.

```lua
local chowcho = require('chowcho')
chowcho.setup({
  -- Must be a single character. The length of the array is the maximum number of windows that can be moved.
  labels = { "A", "B", "C", "D", "E", "F", "G", "H", "I" },
  use_exclude_default = true,
  ignore_case = true,
  selector = {
    float = {
      border_style = "rounded",
      icon_enabled = true,
      color = {
        label = {
          active = "#c8cfff",
          inactive = "#ababab",
        },
        text = {
          active = "#fefefe",
          inactive = "#d0d0d0",
        },
        border = {
          active = "#b400c8",
          inactive = "#fefefe",
        },
      },
      zindex = 1,
    },
    statusline = {
      color = {
        label = {
          active = "#fefefe",
          inactive = "#d0d0d0",
        },
        text = {
          active = "#fefefe",
          inactive = "#d0d0d0",
        },
        background = {
          active = "#3d7172",
          inactive = "#203a3a",
        },
      },
    },
  },
})

vim.keymap.set('n', '<C-w>w',
  function ()
    chowcho.run()
  end,
  { noremap = true }
)
```

**Comment by tkmpypy** [comment]
@s-show 
Thanks for the report!
at #18.
- Don't get default highlights if explicit color is specified
- Add nil check when getting default highlight

I tried to do this.
Please update the plugin and see if the event has improved!
